foodproject/foodapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'foodapp'

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('food/<int:food_id>/', views.details, name='details'),
    path('add/', views.adding, name='adding'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
  ]

foodproject/foodproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodproject/foodapp/models.py
from django.db import models

# Create your models here.
class foodtab(models.Model):
    name = models.CharField(max_length=250)
    ingre = models.TextField()
    desc = models.TextField()
    image = models.ImageField(upload_to='photos')

    def __str__(self):
        return self.name

foodproject/foodapp/forms.py
from django.forms import forms
from django import forms
from .models import foodtab

class foods(forms.ModelForm):
    class Meta:
        model = foodtab
        fields = ['name','ingre','desc','image']

foodproject/foodapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from foodapp.forms import foods
from foodapp.models import foodtab


# Create your views here.
def index(request):
    obj = foodtab.objects.all()
    return render(request,"index.html",{'result':obj})

def details(request, food_id):
        obj2 =foodtab.objects.get(id=food_id)
        return render(request, "details.html", {'result2': obj2})

def adding(request):
    if request.method == "POST":
        fname=request.POST.get('name')
        fingre = request.POST.get('ingre')
        fdesc = request.POST.get('desc')
        fimage = request.FILES['image']
        food = foodtab(name=fname,ingre=fingre,desc=fdesc,image=fimage)
        food.save()
    return render(request, "add.html")

def update(request,id):
    foodobj = foodtab.objects.get(id=id)
    form = foods(request.POST or None, request.FILES, instance=foodobj)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'result3':form, 'result4':foodobj})
def delete(request,id):
    if request.method=='POST':
        foodobj = foodtab.objects.get(id=id)
        foodobj.delete()
        return redirect('/')
    return render(request,'delete.html')

foodproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the food name"> <br><br>
    <input type="text" name="ingre" placeholder="Enter the ingredients"> <br><br>
    <input type="text" name="desc" placeholder="Enter the receipe"> <br> <br>
    <input type="file" name="image"><br><br>
    <input type="submit">
</form>
{% endblock %}

foodproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
     <title>index</title>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      <img src="{% static 'image1.jpeg' %}" width="45" height="35" class="d-inline-block align-top" alt="No image">
      <h2 style="font-family:stencil">RUCHY </h2></a>

</nav>

{% block body %}
{% endblock %}

</body>
</html>

foodproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    Do you want to delete this food item????
    <input type="submit">
    {% endblock %}
</form>

foodproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{result2.image.url}}" width="350" height="350">
        </div>
        <div class="col-md-6">
            <h1 style="font-family:Stencil"> {{result2.name}} </h1> <br>
            <h6 style="font-family:Elephant">INGREDIENTS</h6>
            <h5 style="font-family:Timesnewroman">{{result2.ingre}}</h5>
            <h6 style="font-family:Elephant">HOW TO COOK??</h6>
            <h5 style="font-family:Timesnewroman">{{result2.desc}}</h5>
            <!--urls-path-name-update-->
<a class="btn btn-primary" href="{% url 'foodapp:update' result2.id %}">  Update </a>
<a class="btn btn-danger" href="{% url 'foodapp:delete' result2.id %}">  Delete </a>

        </div>

 </div>
</div>
{% endblock %}

foodproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
<!--    form from views.py-->
    <br>
    {{result3.as_p}} <br>
    <input type="submit">
</form>
{% endblock %}

foodproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" width="100px" height="250px">
  <div class="card-body">
    <h5 style="font-family:Elephant" class="card-title">{{i.name}}</h5>

    <a href="{% url 'foodapp:details' i.id %}" class="btn btn-primary"> <h6 style="font-family:Forte">View more..</h6></a>
  </div>
</div>
        </div>
     {% endfor %}
    </div>

</div>

{% endblock %}